### ISSUE TITLE
Cant log in as admin

### ISSUE THREAD

**Issue by kaimakes** [dandv/instagram-clone#4]
Having a bit of an issue setting up the admin panel - maybe it is something I missed?

Do I need to use Meteor to log in directly?

Im new to Meteor, thanks for the help.

**Comment by dandv** [comment]
There is no admin panel; if you see any "admin" in the code, it's because for simplicity, I've hardcoded myself as the admin to be able to delete blank pictures that users upload.

You can login with Google, Facebook etc.
